### ISSUE TITLE
写的很好，能来一个kindeditor的么？

### ISSUE THREAD

**Issue by hulang** [hbh112233abc/ueditor#3]
主要是ueditor有点笨重。。。

**Comment by hbh112233abc** [comment]
额 我就是喜欢ueditor 功能比较齐全啊! 我们站点的kindeditor刚被我换ueditor呢

**Comment by hulang** [comment]
@hbh112233abc 嗯，我试着也换。。。遇到ueditor的扩展问题，kindeditor简单点。。作者老大。你对ueditor扩展会么？
1、复制文章带有图片的，就自动上传。
2、扩展一个下拉菜单自定义插入到光标处。。。

**Comment by hbh112233abc** [comment]
2、扩展一个下拉菜单自定义插入到光标处。。。 
这是啥意思呢?
1这功能可以搞哦 有空可以加我q370520958 一起搞啊

**Comment by hulang** [comment]
@hbh112233abc 第一个，ue的解决了。
第2个。我只会写到ueditor.all.js里面，界面上，在最后一个按钮。我想写成插件。任意位置。

**Comment by hulang** [comment]
@hbh112233abc 我是从这里下载的。https://github.com/HaoChuan9421/vue-ueditor-wrap/tree/master/assets/downloads

**Comment by hulang** [comment]
这是我写到ueditor.all.js里面的

    UE.registerUI('wx', function (editor, uiName) {
        var objItems = [
            { name: '[昵称]' },
            { name: '[电话]' },
            { name: '[微信]' },
            { name: '[二维码]' }
        ];
        //注册按钮执行时的command命令,用uiName作为command名字，使用命令默认就会带有回退操作
        editor.registerCommand(uiName, {
            execCommand: function (cmdName, item) {
                var html = item.value;
                this.execCommand('insertHtml', html);
            }
        });
        //创建下拉菜单中的键值对，这里我用字体大小作为例子
        var items = [];
        for (var i = 0; i < objItems.length; i++) {
            var item = objItems[i];
            items.push({
                //显示的条目
                label: item['name'],
                //选中条目后的返回值
                value: item['name']
            });
        }
        //创建下拉框
        var combox = new UE.ui.Combox({
            //需要指定当前的编辑器实例
            editor: editor,
            //添加条目
            items: items,
            //当选中时要做的事情
            onselect: function (t, index) {
                //拿到选中条目的值
                editor.execCommand(uiName, this.items[index]);
                //t.setValue(t.initValue);
            },
            //提示
            title: '微信相关',
            //当编辑器没有焦点时，combox默认显示的内容
            initValue: '微信相关'
        });
        return combox;
    });

![QQ截图20200828121229](https://user-images.githubusercontent.com/4961831/91520405-c9642000-e927-11ea-9c37-93cf4dc85de6.png)
在界面是最后的位置，怎么写成插件，随意放位置呢？

**Comment by hbh112233abc** [comment]
![QQ截图20200830212459](https://user-images.githubusercontent.com/7788164/91660183-5ca77c00-eb07-11ea-88aa-3850b5d57df5.jpg)
`ueditor.all.js`主要代码:
```
editorui.social = function (editor,list,title) {
        title = editor.options.labelMap['social'] || editor.getLang("labelMap.social") || '';
        list = list || editor.options['social'] || [];
        if (!list.length) return;
        var ui = new editorui.Combox({
            editor: editor,
            items: list,
            title: title,
            initValue: title,
            onselect: function (t, index) {
                editor.execCommand('social', this.items[index]);
            },
            onbuttonclick: function () {
                this.showPopup();
            }
        });
        editorui.buttons['social'] = ui;
        editor.addListener('selectionchange', function (type, causeByUi, uiReady) {
            if (!uiReady) {
                var state = editor.queryCommandState('social');
                if (state == -1) {
                    ui.setDisabled(true);
                } else {
                    ui.setDisabled(false);
                    ui.setValue(editor.queryCommandValue('social'));
                }
            }

        });
        return ui;
    };
```
```
/**
 * 社交标签
 * 用于插入社交相关账号信息
 */
UE.plugins['social'] = function(){ 
    var me=this;  
    me.setOpt('social',[
        {label:'昵称',value:'hbh',type:'text'},
        {label:'微信',value:'huangbinghe',type:'text'},
        {label:'手机号',value:'18759201163',type:'tel'},
        {label:'邮箱',value:'hbh112233abc@163.com',type:'mail'},
        {label:'二维码',value:'https://p.ssl.qhimg.com/d/inn/0444533a/Snip20160525_6.png',type:'img'},
    ]);
    //注册鼠标和键盘事件  
    me.addListener('mousedown',function(){}); 
    me.addListener('keydown',function(type,evt){}); 
    me.addListener('mouseup',function(){}); 

    me.commands['social'] = {
        //查询当前命令状态  
        queryCommandState: function(cmdName){
            // console.log('query cmd state:',cmdName);
        },
        //命令执行主体  
        execCommand: function(cmdName,item){
            // console.log(item);
            var html = '<p>';
            switch(item.type){
                case 'text':
                    html += '<span>'+item.value+'</span>';
                    break;
                case 'url':
                    html += '<a href="'+item.value+'">'+item.label+'</a>';
                    break;
                case 'tel':
                    html += '<a href="tel:'+item.value+'">'+item.value+'</a>';
                    break;
                case 'sms':
                    html += '<a href="sms:'+item.value+'">'+item.value+'</a>';
                    break;
                case 'mail':
                    html += '<a href="mailto:'+item.value+'">'+item.value+'</a>';
                    break;  
                case 'img':
                    html += '<img src="'+item.value+'">';
                    break;
                default:
                    html += item.value;
                    break;                  
            }
            html += '</p>';
            me.execCommand('insertHtml',html);
        },
        //获取命令执行结果  
        queryCommandValue: function(cmdName){
            return me.options.labelMap['social'] || me.getLang("labelMap.social") || '社交账号';
        }, 
    }
}; 
```
然后可以配置ueditor.config.js
```
,social:[
        {label:'昵称',value:'昵称',type:'text'},
        {label:'微信',value:'微信号',type:'text'},
        {label:'手机号',value:'手机号',type:'tel'},
        {label:'邮箱',value:'邮箱',type:'mail'},
        {label:'二维码',value:'二维码链接',type:'img'},
],
```

**Comment by hbh112233abc** [comment]
版本发布了 你可以看看参考一下 增加了style设置的支持

**Comment by hulang** [comment]
@hbh112233abc 感谢啊。。这么晚了还再更新

**Comment by hulang** [comment]
@hbh112233abc 作者老大，你有https://gitee.com/的么？国外，我下载太慢了。。

**Comment by hbh112233abc** [comment]
https://gitee.com/hbh112233abc/ueditor

**Comment by hulang** [comment]
@hbh112233abc 收到
