### ISSUE TITLE
UE.getEditor is not a function

### ISSUE THREAD

**Issue by chenvle** [hbh112233abc/ueditor#4]
![image](https://user-images.githubusercontent.com/41420442/92366752-23cf5e80-f128-11ea-8cda-f9d618b81125.png)

**Comment by hbh112233abc** [comment]
额 这是怎么出现的错误呢? 你那边引入的ueditor.all.min.js是不是最新的呢?

**Comment by chenvle** [comment]
是最新的，昨天下载的

**Comment by hbh112233abc** [comment]
qq多少 远程看看 可以么

**Comment by chenvle** [comment]
mac 开不了远程，可以截图给你
qq：541052346

**Comment by hbh112233abc** [comment]
因为v1.2.0版本js有更新
composer update 之后需要执行
```
php think ueditor:publish
```
覆盖最新的静态资源文件
