### ISSUE TITLE
配置信息表不存在，查看了下代码，作者你没有获取表名前缀

### ISSUE THREAD

**Issue by hulang** [hbh112233abc/ueditor#5]
.....................
    /**
     * 判断数据表是否存在
     *
     * @param string $tableName
     * @return bool
     */
    protected function tableExists(string $tableName = 'ueditor_config')
    {
        // 获取数据库配置
        $config = config('database');
        // 获取数据库表前缀
        $dbPrefix = $config['connections']['mysql']['prefix'];
        // 组合表名
        $name = $dbPrefix . $tableName;
        $res = Db::query('show tables like "' . $name . '";');
        return !empty($res);
    }

**Comment by hulang** [comment]
另外，配置文件里面，能否加个，是否开启验证，每次得弄：.env来配置。。。。

**Comment by hbh112233abc** [comment]
> // 获取数据库配置
> $config = config('database');
> // 获取数据库表前缀
> $dbPrefix = $config['connections']['mysql']['prefix'];
> // 组合表名
> $name = $dbPrefix . $tableName;
> $res = Db::query('show tables like "' . $name . '";');

感谢你的反馈,不过不知道你有没有主要到查询都是Db::table('ueditor_config')开头的,其实刚开始设计表名就只是`ueditor_config`,没考虑加前缀的, 如果你执行`php think migrate:run` 数据库会自动创建`ueditor_config`的表啊.

或者考虑在`config`里加`table_name`,默认为`ueditor_config`,如果你们为了数据表命名格式统一加了前缀,到时配置一下`config.table_name`是不是更好呢

**Comment by hbh112233abc** [comment]
> 另外，配置文件里面，能否加个，是否开启验证，每次得弄：.env来配置。。。。

你说的这个是开启哪个验证呢?

**Comment by hulang** [comment]
@hbh112233abc 运行命令那块，默认会加上表的前缀，就是查询没有，所以来反馈的

**Comment by hbh112233abc** [comment]
> @hbh112233abc 运行命令那块，默认会加上表的前缀，就是查询没有，所以来反馈的

确实是哦,太感谢了,马上修复! 还有你说的配置文件开启验证是什么意思呢?
